---
title: Arr Stack
background:
  image: https://images.unsplash.com/photo-1557264337-e8a93017fe92?q=80&w=2070
  blur: xl
  saturate: 20
  brightness: 50

theme: dark
color: slate

headerStyle: clean

maxGroupColumns: 3
useEqualHeights: true

layout:
  Media:
    style: column
    header: true
  Downloads:
    style: column
    header: true
  Monitoring:
    style: column
    header: true
