---
title: Arr Stack
background:
  image: https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1920
  blur: sm
  opacity: 50

theme: dark
color: slate

headerStyle: clean

fiveColumns: false

layout:
  Media:
    style: column
    header: true
  Downloads:
    style: column
    header: true
  Monitoring:
    style: column
    header: true
